### ISSUE TITLE
Сделать лаяут для выведения базы данных

### ISSUE THREAD

**Issue by T1mOnchik** [T1mOnchik/Where-To-Flight#6]
Лаяут куда будет выводиться история полетов из базы данных

**Comment by T1mOnchik** [comment]
время, дата, сортиировка(самый новый наверху),

**Comment by T1mOnchik** [comment]
если нет истории то выводить "there no recent history"(label)

**Comment by 4eburek** [comment]
1. Remove upper caption
2. Use italic for center caption
